site_name: Lupoex Documentation
pages:
  - 'index.md'
  - Getting Started:
    - Overview: 'getting-started/overview.md'
    - Create An Account: 'getting-started/create-an-account.md'
    - Log In: 'getting-started/log-in.md'
    - View Your First Market: 'getting-started/view-your-first-market.md'
theme: material
site_favicon: 'images/favicon.ico'
markdown_extensions:
  - admonition
extra_css:
  - 'styles/extra.css'
extra:
  logo: 'images/lupoex-logo.png'
  palette:
    primary: 'light blue'
    accent: 'light blue'
#  logo: 'images/logo.svg'
#  social:
#      - type: 'github'
#        link: 'https://github.com/squidfunk'
#      - type: 'twitter'
#        link: 'https://twitter.com/squidfunk'
#      - type: 'linkedin'
#        link: 'https://de.linkedin.com/in/martin-donath-20a95039'
#  google_analytics:
#    - 'UA-XXXXXXXX-X'
#    - 'auto'