site_name: Lupoex Documentation
pages:
  - 'index.md'
  - Getting Started: 'getting-started.md'
  - Viewing Your First Market: 'viewing-your-first-market.md'
  - Terms And Conditions: 'terms-and-conditions.md'
theme: material
site_favicon: 'images/favicon.ico'
markdown_extensions:
  - admonition
extra_css:
  - 'styles/extra.css'
extra:
  logo: 'images/lupoex-logo.png'
  palette:
    primary: 'light blue'
    accent: 'light blue'
#  logo: 'images/logo.svg'
#  social:
#      - type: 'github'
#        link: 'https://github.com/squidfunk'
#      - type: 'twitter'
#        link: 'https://twitter.com/squidfunk'
#      - type: 'linkedin'
#        link: 'https://de.linkedin.com/in/martin-donath-20a95039'
#  google_analytics:
#    - 'UA-XXXXXXXX-X'
#    - 'auto'